<a href="https://colab.research.google.com/github/nefetorve/cwiczenia_data_science/blob/master/031_040_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 31](#1)
* [Ćwiczenie 32](#2)
* [Ćwiczenie 33](#3)
* [Ćwiczenie 34](#4)
* [Ćwiczenie 35](#5)
* [Ćwiczenie 36](#6)
* [Ćwiczenie 37](#7)
* [Ćwiczenie 38](#8)
* [Ćwiczenie 39](#9)
* [Ćwiczenie 40](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'1.18.5'

### <a name='1'></a> Ćwiczenie 31
Wykonaj dwa sortowania podanej poniżej tablicy $A$:
* wierszowo (rosnąco)
* kolumnowo (rosnąco)


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.sort()_.

In [5]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

np.sort(A,axis=0)

array([[ 1.99,  2.39,  4.99],
       [ 4.99,  3.49,  7.29],
       [14.99,  9.99,  9.99]])

In [6]:
np.sort(A,axis=1)

array([[ 3.49,  4.99,  9.99],
       [ 1.99,  4.99,  9.99],
       [ 2.39,  7.29, 14.99]])

### <a name='2'></a> Ćwiczenie 32
Wytnij wszystkie elementy tablicy $A$ o wartości wyższej niż 8.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



In [7]:
A[A>8]

array([ 9.99,  9.99, 14.99])

### <a name='3'></a> Ćwiczenie 33
Podana jest poniższa tablica $A$. Zastąp elementy powyżej wartości 10 wartością stałą 10 (obcięcie wartości do 10).


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.where()_.

In [13]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
A[A>10] = 10
A

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

In [25]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

np.where(A>10.0, 10, A)

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

### <a name='4'></a> Ćwiczenie 34
Poniższą dwuwymiarową tablicę $A$ przedstaw w postaci 'wypłaszczonej' jednowymiarowej tablicy.  

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Oczekiwany wynik:__


```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Wskazówka:__ Użyj funkcji _np.ravel()_.




In [27]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

np.ravel(A)

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

### <a name='5'></a> Ćwiczenie 35
Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 0.0.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Oczekiwany wynik:__


```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```





__Wskazówka:__ Użyj funkcji _np.zeros_like()_.

In [29]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

np.zeros_like(A)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### <a name='6'></a> Ćwiczenie 36

Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 9.99.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

__Oczekiwany wynik:__


```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```



__Wskazówka:__ Użyj funkcji _np.full_like()_.

In [34]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

np.full_like(A, '9.99')

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

### <a name='7'></a> Ćwiczenie 37
Zbuduj tablicę dwuwymiarową (macierz kwadratową dolną trójkątną) podnaną poniżej:


```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
__Wskazówka:__ Użyj funkcji _np.tri()_.


In [32]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

### <a name='8'></a> Ćwiczenie 38
Stwórz dowolną tablicę 3-wymiarową o kształcie $(2, 3, 4)$.

In [ ]:
A = np.array()

### <a name='9'></a> Ćwiczenie 39

Wygeneruj dwuwymiarową tablicę o kształcie _(200, 300)_ wypełnioną wartościami losowymi od 0 do 255 włacznie i typie danych _np.uint8_ i przypisz do zmiennej _image_.

In [ ]:
# tutaj wpisz rozwiązanie

Nastepnie uruchom poniższy blok kodu. W rezultacie uzyskasz podgląd na losowo wygenerowany czarno-biały obraz.

In [ ]:
from google.colab.patches import cv2_imshow

cv2_imshow(image)

### <a name='10'></a> Ćwiczenie 40
Tablicę _image_ z poprzedniego zadania posortuj wzdłuż wiersza rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie

Tablicę _image_ z poprzedniego zadania posortuj wzdłuż kolumny rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie