<a href="https://colab.research.google.com/github/nefetorve/cwiczenia_data_science/blob/master/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [46]:
import numpy as np

np.random.seed(42)
np.__version__

'1.18.5'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [47]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A,B),axis=0)


array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [48]:
np.concatenate((A,B),axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [49]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate((data,target),axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [50]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1,feature2,feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [51]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])

In [52]:
A1, A2, A3 = np.split(A,[2,6],axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [53]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)
A

array([[1, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [54]:
np.count_nonzero(A, axis=1)

array([4, 2, 1, 5, 4, 3, 3, 6, 4, 6])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [55]:
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
A

array([[ 0.7385,  0.1714, -0.1156, -0.3011],
       [-1.4785, -0.7198, -0.4606,  1.0571],
       [ 0.3436, -1.763 ,  0.3241, -0.3851],
       [-0.6769,  0.6117,  1.031 ,  0.9313],
       [-0.8392, -0.3092,  0.3313,  0.9755],
       [-0.4792, -0.1857, -1.1063, -1.1962],
       [ 0.8125,  1.3562, -0.072 ,  1.0035],
       [ 0.3616, -0.6451,  0.3614,  1.538 ],
       [-0.0358,  1.5646, -2.6197,  0.8219],
       [ 0.087 , -0.299 ,  0.0918, -1.9876]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [56]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=1)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [57]:
A = np.random.randn(8, 4)
A

array([[-0.21967189,  0.35711257,  1.47789404, -0.51827022],
       [-0.8084936 , -0.50175704,  0.91540212,  0.32875111],
       [-0.5297602 ,  0.51326743,  0.09707755,  0.96864499],
       [-0.70205309, -0.32766215, -0.39210815, -1.46351495],
       [ 0.29612028,  0.26105527,  0.00511346, -0.23458713],
       [-1.41537074, -0.42064532, -0.34271452, -0.80227727],
       [-0.16128571,  0.40405086,  1.8861859 ,  0.17457781],
       [ 0.25755039, -0.07444592, -1.91877122, -0.02651388]])

In [58]:
np.delete(A,2,axis=1)

array([[-0.21967189,  0.35711257, -0.51827022],
       [-0.8084936 , -0.50175704,  0.32875111],
       [-0.5297602 ,  0.51326743,  0.96864499],
       [-0.70205309, -0.32766215, -1.46351495],
       [ 0.29612028,  0.26105527, -0.23458713],
       [-1.41537074, -0.42064532, -0.80227727],
       [-0.16128571,  0.40405086,  0.17457781],
       [ 0.25755039, -0.07444592, -0.02651388]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [59]:
v = np.array([3, 4, -2])

In [60]:
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [61]:
A = np.random.randint(10, size=(100, 30))
A

array([[0, 7, 0, 0, 1, 1, 5, 6, 4, 0, ..., 0, 5, 7, 4, 3, 1, 5, 5, 0, 8],
       [5, 2, 3, 3, 2, 9, 2, 2, 3, 6, ..., 1, 6, 9, 2, 6, 9, 8, 3, 0, 1],
       [0, 4, 4, 6, 8, 8, 2, 2, 2, 3, ..., 7, 3, 2, 8, 2, 8, 1, 1, 1, 5],
       [2, 8, 3, 0, 3, 0, 4, 3, 7, 7, ..., 2, 5, 7, 1, 4, 0, 0, 4, 2, 3],
       [2, 0, 0, 4, 5, 2, 8, 4, 7, 0, ..., 9, 5, 9, 2, 7, 7, 1, 5, 6, 1],
       [9, 1, 9, 0, 7, 0, 8, 5, 6, 9, ..., 3, 0, 7, 2, 6, 1, 1, 6, 5, 2],
       [8, 9, 5, 9, 9, 5, 0, 3, 9, 5, ..., 2, 6, 7, 3, 1, 9, 2, 0, 7, 2],
       [9, 6, 9, 4, 9, 4, 6, 8, 4, 0, ..., 4, 5, 6, 2, 9, 2, 4, 5, 8, 4],
       [0, 3, 4, 9, 9, 4, 6, 3, 0, 4, ..., 2, 9, 0, 7, 4, 3, 7, 6, 1, 0],
       [3, 7, 1, 2, 0, 0, 2, 4, 2, 0, ..., 7, 9, 9, 9, 1, 2, 8, 6, 3, 9],
       ...,
       [6, 3, 5, 2, 5, 1, 7, 1, 6, 8, ..., 9, 7, 2, 9, 0, 8, 0, 2, 7, 2],
       [3, 7, 0, 5, 0, 0, 7, 3, 0, 9, ..., 0, 8, 0, 7, 4, 2, 6, 6, 8, 6],
       [2, 0, 7, 2, 7, 7, 4, 0, 9, 6, ..., 1, 3, 0, 3, 1, 4, 2, 7, 3, 0],
       [0, 9, 2, 8, 6, 1, 

In [62]:
np.set_printoptions(edgeitems=10)
A

array([[0, 7, 0, 0, 1, 1, 5, 6, 4, 0, ..., 0, 5, 7, 4, 3, 1, 5, 5, 0, 8],
       [5, 2, 3, 3, 2, 9, 2, 2, 3, 6, ..., 1, 6, 9, 2, 6, 9, 8, 3, 0, 1],
       [0, 4, 4, 6, 8, 8, 2, 2, 2, 3, ..., 7, 3, 2, 8, 2, 8, 1, 1, 1, 5],
       [2, 8, 3, 0, 3, 0, 4, 3, 7, 7, ..., 2, 5, 7, 1, 4, 0, 0, 4, 2, 3],
       [2, 0, 0, 4, 5, 2, 8, 4, 7, 0, ..., 9, 5, 9, 2, 7, 7, 1, 5, 6, 1],
       [9, 1, 9, 0, 7, 0, 8, 5, 6, 9, ..., 3, 0, 7, 2, 6, 1, 1, 6, 5, 2],
       [8, 9, 5, 9, 9, 5, 0, 3, 9, 5, ..., 2, 6, 7, 3, 1, 9, 2, 0, 7, 2],
       [9, 6, 9, 4, 9, 4, 6, 8, 4, 0, ..., 4, 5, 6, 2, 9, 2, 4, 5, 8, 4],
       [0, 3, 4, 9, 9, 4, 6, 3, 0, 4, ..., 2, 9, 0, 7, 4, 3, 7, 6, 1, 0],
       [3, 7, 1, 2, 0, 0, 2, 4, 2, 0, ..., 7, 9, 9, 9, 1, 2, 8, 6, 3, 9],
       ...,
       [6, 3, 5, 2, 5, 1, 7, 1, 6, 8, ..., 9, 7, 2, 9, 0, 8, 0, 2, 7, 2],
       [3, 7, 0, 5, 0, 0, 7, 3, 0, 9, ..., 0, 8, 0, 7, 4, 2, 6, 6, 8, 6],
       [2, 0, 7, 2, 7, 7, 4, 0, 9, 6, ..., 1, 3, 0, 3, 1, 4, 2, 7, 3, 0],
       [0, 9, 2, 8, 6, 1, 